language: bash
services:
  - docker
sudo: required
before_install:
  - export TZ='Asia/Shanghai'
script:
  - docker --version
after_success:
  - echo $docker_pwd | docker login -u "zyunv513" --password-stdin
  - docker build . -t "zyunv513/docker-learn:latest"
  - docker push zyunv513/docker-learn:latest
  - chmod 600 id_rsa
  - sshpass -p $server_pwd ssh -o "StrictHostKeyChecking no" -i id_rsa root@$server_ip "cd /opt/project;sudo docker-compose -f docker-compose.yml pull;sudo docker-compose -f docker-compose.yml
    up -d;exit"
