language: bash
services:
  - docker
sudo: required
before_install:
  - export TZ='Asia/Shanghai'
script:
  - docker build . -t "docker-learn:latest"
after_success:
  - docker login --username=zyunv513 -p=$docker_pwd dockerhub
  - docker push dockerhub:latest
  - chmod 600 id_rsa
  - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$server_ip "cd /opt/project;sudo docker-compose -f docker-compose.yml pull;sudo docker-compose -f docker-compose.yml up -d;exit"
deploy:
  provider: pages
  github-token: $GH_TOKEN
  on:
    branch: project-deploy
