sudo: required
language: node_js
node_js: stable
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_8e3301ed1bb3_key -iv $encrypted_8e3301ed1bb3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 102.201.64.94\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - npm run test
