language: node_js
node_js: stable
cache:
  directories:
    - node_modules # 依赖缓存的目录
before_install:
  - export TZ='Asia/Shanghai' # 设置时区
deploy:
  provider: pages
  github-token: $GH_TOKEN # github 上的token环境变量
  on:
    branch: project-deploy
