language: bash
services:
- docker
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_016c31bb718f_key -iv $encrypted_016c31bb718f_iv
  -in nopwd.enc -out ~/.ssh/nopwd -d
- export TZ='Asia/Shanghai'
script:
- docker build . -t "zyunv513/docker-learn:latest"
after_success:
- echo $docker_pwd | docker login -u "zyunv513" --password-stdin
- docker push zyunv513/docker-learn:latest
- chmod 600 id_rsa
- ssh -o "StrictHostKeyChecking no" -i id_rsa root@$server_ip "cd /opt/project;sudo
  docker-compose -f docker-compose.yml pull;sudo docker-compose -f docker-compose.yml
  up -d;exit"
