language: node_js
node_js: stable
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_1dc0466c3d69_key -iv $encrypted_1dc0466c3d69_iv
  -in nopwd.enc -out ~/.ssh/nopwd -d
# - chmod 600 ~/.ssh/id_rsa
# - echo -e "Host 102.201.64.94\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
